name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.ee2ef7cc-e76f-426f-b6d7-8b926e41091e }}
          GH_TOKEN: ${{ secrets.6951d935de233d97b3c1e7f4eff37e005a84b553 }}